<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit57adfe89bb66fb6777466b269dd182d7
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MailchimpTests\\' => 15,
            'MailchimpAPI\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MailchimpTests\\' => 
        array (
            0 => __DIR__ . '/..' . '/jhut89/mailchimp3php/tests',
        ),
        'MailchimpAPI\\' => 
        array (
            0 => __DIR__ . '/..' . '/jhut89/mailchimp3php/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit57adfe89bb66fb6777466b269dd182d7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit57adfe89bb66fb6777466b269dd182d7::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
